### ISSUE TITLE
Successful build on first-run on clean Ubuntu machine

### ISSUE THREAD

**Issue by MarshallOfSound** [electron/build-tools#105]
Running `e init` on a clean Linux (Ubuntu) machine should work first time and self-correct missing dependencies along the way (by prompting the user or by auto running commands) so that it will build Electron with no prompts and with maximum goma cache hits.

Chose Ubuntu here as it's probably the easiest support and the most commonly used in a VM for development.

**Comment by MarshallOfSound** [comment]
Doing a clean build on an ubuntu machine.  Things we need to check for and warn about up front.

* `pkg-config`
* `gperf`

**Comment by bnb** [comment]
Also encountered on codespaces:

* `lsof`

**Comment by codebytere** [comment]
Closing as generally working - if issues crop up we can file more specific bugs.
