### ISSUE TITLE
`e init` fails on Windows when there are spaces in a directory name

### ISSUE THREAD

**Issue by strega-nil** [electron/build-tools#133]
The full text of the error is here: https://gist.github.com/strega-nil/32b1eee85f5c24e8f648e41ce7552ecb

The important part looks like it's here:

```
gclient_utils(833) enqueue:enqueued(src/electron)
gclient(565) requirements:Dependency(src/electron).requirements = ()
gclient(565) requirements:Dependency(src/electron).requirements = ()
gclient_utils(1011) __init__:_Worker(src/electron) reqs:()
gclient_utils(1020) run:_Worker.run(src/electron)
gclient(916) run:Dependency(src/electron).run()
subprocess2(154) __init__:git --version;  cwd=.
gclient_utils(1036) run:Caught exception in thread src/electron
gclient_utils(1037) run:(<class 'FileNotFoundError'>, FileNotFoundError(2, 'The system cannot find the file specified', None, 2, None), <traceback object at 0x000001D5F174A700>)
gclient_utils(1040) run:_Worker.run(src/electron) done
```

**Comment by codebytere** [comment]
If you open cmd/powershell and type `where python` - does the `depot_tools` `python.bat` come ahead of any copies of `python.exe`?

**Comment by strega-nil** [comment]
No, it does not; there is no place I could see that would set `depot_tools`'s `python.bat` on the path at all.

**Comment by codebytere** [comment]
Try running `gclient` just by itself first? We follow this for the most part: https://chromium.googlesource.com/chromium/src/+/master/docs/windows_build_instructions.md#Setting-up-Windows

And i didn't have this happen on my local win config so perhaps it's a strange system thing, unclear 🤔

**Comment by strega-nil** [comment]
Ah, looks like it might be an issue with spaces in my electron build-tools directory...

**Comment by strega-nil** [comment]
eeyup, apparently `gclient` doesn't support being run in a directory tree that contains spaces.

**Comment by codebytere** [comment]
@strega-nil did it sync successfully then?

**Comment by strega-nil** [comment]
@codebytere it didn't, see #134; it just got further.

**Comment by ckerr** [comment]
@strega-nil does #178 fix this for you?

**Comment by codebytere** [comment]
Closing due to above
