### ISSUE TITLE
The variable "goma_dir" was set as a build argument

### ISSUE THREAD

**Issue by AlvinZhangH** [electron/build-tools#170]
C:\Users\x99999\src\electron>gn.bat gen "out/Testing0903" --args="import(\"//electron/build/args/testing.gn\") import(\"D:\electron\0827\000\build-tools-master\third_party\goma.gn\")
ERROR at /D:/electron/0827/000/build-tools-master/third_party/goma.gn:1:12: Build argument has no effect.
goma_dir = "D:\electron\0827\000\build-tools-master\third_party\goma"
           ^---------------------------------------------------------
The variable "goma_dir" was set as a build argument
but never appeared in a declare_args() block in any buildfile.

To view possible args, run "gn args --list <builddir>"
ERROR No targets.
I could not find any targets to write, so I'm doing nothing.
ERROR

**Comment by codebytere** [comment]
Closing as nonreproducible
