### ISSUE TITLE
download Dependency squirrel.mac all the time

### ISSUE THREAD

**Issue by chengfengliu** [electron/build-tools#176]
`
[0:11:40] Still working on:
[0:11:40]   src
gclient(555) requirements:Dependency(src/third_party/electron_node).requirements = ('src', 'src/electron')
gclient(555) requirements:Dependency(src/third_party/nan).requirements = ('src', 'src/electron')
gclient(555) requirements:Dependency(src/third_party/squirrel.mac).requirements = ('src', 'src/electron')
gclient(555) requirements:Dependency(src/third_party/squirrel.mac/vendor/Mantle).requirements = ('src', 'src/electron', 'src/third_party/squirrel.mac')
gclient(555) requirements:Dependency(src/third_party/squirrel.mac/vendor/ReactiveObjC).requirements = ('src', 'src/electron', 'src/third_party/squirrel.mac')
[0:11:50] Still working on:
[0:11:50]   src
gclient(555) requirements:Dependency(src/third_party/electron_node).requirements = ('src', 'src/electron')
gclient(555) requirements:Dependency(src/third_party/nan).requirements = ('src', 'src/electron')
gclient(555) requirements:Dependency(src/third_party/squirrel.mac).requirements = ('src', 'src/electron')
gclient(555) requirements:Dependency(src/third_party/squirrel.mac/vendor/Mantle).requirements = ('src', 'src/electron', 'src/third_party/squirrel.mac')
gclient(555) requirements:Dependency(src/third_party/squirrel.mac/vendor/ReactiveObjC).requirements = ('src', 'src/electron', 'src/third_party/squirrel.mac')
[0:12:00] Still working on:
[0:12:00]   src
gclient(555) requirements:Dependency(src/third_party/electron_node).requirements = ('src', 'src/electron')
gclient(555) requirements:Dependency(src/third_party/nan).requirements = ('src', 'src/electron')
gclient(555) requirements:Dependency(src/third_party/squirrel.mac).requirements = ('src', 'src/electron')
gclient(555) requirements:Dependency(src/third_party/squirrel.mac/vendor/Mantle).requirements = ('src', 'src/electron', 'src/third_party/squirrel.mac')
gclient(555) requirements:Dependency(src/third_party/squirrel.mac/vendor/ReactiveObjC).requirements = ('src', 'src/electron', 'src/third_party/squirrel.mac')
[0:12:10] Still working on:
[0:12:10]   src
gclient(555) requirements:Dependency(src/third_party/electron_node).requirements = ('src', 'src/electron')
gclient(555) requirements:Dependency(src/third_party/nan).requirements = ('src', 'src/electron')
gclient(555) requirements:Dependency(src/third_party/squirrel.mac).requirements = ('src', 'src/electron')
gclient(555) requirements:Dependency(src/third_party/squirrel.mac/vendor/Mantle).requirements = ('src', 'src/electron', 'src/third_party/squirrel.mac')
gclient(555) requirements:Dependency(src/third_party/squirrel.mac/vendor/ReactiveObjC).requirements = ('src', 'src/electron', 'src/third_party/squirrel.mac')
[0:12:20] Still working on:
[0:12:20]   src
gclient(555) requirements:Dependency(src/third_party/electron_node).requirements = ('src', 'src/electron')
gclient(555) requirements:Dependency(src/third_party/nan).requirements = ('src', 'src/electron')
gclient(555) requirements:Dependency(src/third_party/squirrel.mac).requirements = ('src', 'src/electron')
gclient(555) requirements:Dependency(src/third_party/squirrel.mac/vendor/Mantle).requirements = ('src', 'src/electron', 'src/third_party/squirrel.mac')
gclient(555) requirements:Dependency(src/third_party/squirrel.mac/vendor/ReactiveObjC).requirements = ('src', 'src/electron', 'src/third_party/squirrel.mac')
`

for 50 minutes

**Comment by LuciferLat** [comment]
+1 me too same issue

**Comment by MarshallOfSound** [comment]
Those logs are unfortunately misleading, it isn't downloading squirrel.mac, it's downloading all the dependencies of those repos.   The initial checkout downloads a _lot_ of stuff and on slower internet connections it can take _hours_
