### ISSUE TITLE
evm config migration doesn't persist

### ISSUE THREAD

**Issue by samuelmaddock** [electron/build-tools#181]
OS: Windows 10 Pro 64-bit (2004)

After running `e build`, I'm informed that my configuration is outdated and will be updated for me. However, each time I run `e build`, I get the same warning.

```
D:\work\electron>e build
WARN Your evm config main-testing is using an old remote configuration "{
  origin: {
    electron: 'git@github.com:electron/electron.git',
    node: 'git@github.com:electron/node.git'
  }
}" - we've updated it for you
Updating C:\Users\Sam\.electron_build_tools\third_party\depot_tools
Running "cmd.exe /c C:\Users\Sam\.electron_build_tools\third_party\depot_tools\update_depot_tools.bat"
Running "ninja -j 200 electron" in D:\work\electron\main\src\out\Testing
```

**Comment by MarshallOfSound** [comment]
This is expected behavior, we didn't want to start overwriting peoples configs.  Perhaps we should at least tell y'all how to fix it though.  Or maybe add `e sanitize-config --json` so you can do `e sanitize-config --json > my-config.json` 🤔 

cc @codebytere

**Comment by samuelmaddock** [comment]
What's confusing for me is that it says "we've updated it for you". I was expecting it to be a one time message and for it not to appear again.

If that's replaced with a message saying how to migrate, that's fine too.

**Comment by codebytere** [comment]
imo we can ask the user if they want to overwrite the existing config with a sanitized one here - i agree it's not super clear and we should either 
1) Tweak the message to be more actionable
2) Add overwrite functionality either with a new command or as part of existing checking logic
