### ISSUE TITLE
`e test` wrong module path error

### ISSUE THREAD

**Issue by holmberd** [electron/build-tools#185]
When running `e test --runner=native` it throws an error.

`Error: Cannot find module '/Users/h/.electron_build_tools/src/utils/e`

Looks like the offending line is here.
https://github.com/electron/build-tools/blob/60f81c2226ff4c963d89ec2da96e5d25e1d743e1/src/utils/headers.js#L26

Should probably be `path.resolve(__dirname, '../e')`, alt. future proofing to get the caller directory with the `parent-module`.

**Comment by codebytere** [comment]
@holmberd what operating system was this? never seen this before 🤔

**Comment by holmberd** [comment]
@codebytere MacOS. This code block is only reached when a build is needed, perhaps that is why? Unless there is some information I'm missing.

Current module directory for `headers.js` is `/.../.electron_build_tools/src/utils/`, which is what `__dirname` will resolve to.

`path.resolve(__dirname, '..', 'e')` should resolve to the correct script path, i.e. `/.../.electron_build_tools/src/e`, to execute the arguments.
