### ISSUE TITLE
Usage with existing electron checkout?

### ISSUE THREAD

**Issue by erickzhao** [electron/build-tools#19]
Using an existing Electron checkout that I already had, I seem to be unable to run any commands.

```sh
Configuration '/Users/erickzhao/Developer/electron-gn-scripts/nix/commands/../../generated.env.sh' not found. (Do you need to run 'evm' or 'e fetch'?)
```

As per the error message, I tried to run `evm` to no avail, as I don't already have a `config.yml`:

```sh
Config file: /Users/erickzhao/Developer/electron-gn-scripts/config..yml not found
```

And I don't want to run `e fetch` to install a new Electron build. Is there a way around this?

**Comment by MarshallOfSound** [comment]
Yeah you have to make a config file.  Copy the example config and set it up for your existing checkout.  Then use evm with your new config file
