### ISSUE TITLE
e build electron:dist doesn't remove symbol dist.zip is very large.

### ISSUE THREAD

**Issue by bigben0123** [electron/build-tools#191]
When I use
```
e build electron:dist -v
```
It generates dist.zip, but the size is greater than 1g. 
Can I add strip binaries by e command?

```
electron/script/strip-binaries.py -d out/Release
```

**Comment by bigben0123** [comment]
···
function runStrip(config) {
  depot.ensure();
  //console.log(evmConfig.outDir(config));
  const gnPath = 'electron/script/strip-binaries.py';
  const execArgs = ['-d', `out/${config.gen.out}` ];
  const execOpts = { cwd: path.resolve(config.root, 'src') };

  //delete dist.zip file
  const distfile = [path.resolve(evmConfig.outDir(config),'dist.zip')];
  if (fs.existsSync(distfile[0])){
    console.log('dist.zip delete.');
    depot.execFileSync(config, 'rm', distfile, execOpts);
  }else{
    console.log('dist.zip not found.');
  }

  //strip electron
  depot.execFileSync(config, gnPath, execArgs, execOpts);
}
···

**Comment by bigben0123** [comment]
set it in release.gn:
symbol_level = 0
The electron file will be about 70m.

**Comment by codebytere** [comment]
Closing this in light of comments on https://github.com/electron/build-tools/pull/197
