### ISSUE TITLE
Goma fail when run command  e build

### ISSUE THREAD

**Issue by wuzhiming** [electron/build-tools#196]
OS: Windows 10 Pro 64-bit (Build 18362)
Node: v12.18.0
NPM: 6.14.6
Yarn: 1.22.5
python:2.7.16
![image](https://user-images.githubusercontent.com/6093737/95649991-58fa1280-0b13-11eb-9ef1-7fa59e8571a3.png)

I have install pywin32 but it still get this error ,how can I fix this?

**Comment by dsanders11** [comment]
This looks like it's an issue on your specific computer. Googling the error code shows [this result](https://answers.microsoft.com/en-us/windows/forum/all/file-system-error-1073740791/d0532279-f1a7-4962-8927-4f31b9e00c02) which suggests it has to do with filesystem errors on your hard disk.

**Comment by wuzhiming** [comment]
> This looks like it's an issue on your specific computer. Googling the error code shows [this result](https://answers.microsoft.com/en-us/windows/forum/all/file-system-error-1073740791/d0532279-f1a7-4962-8927-4f31b9e00c02) which suggests it has to do with filesystem errors on your hard disk.

But I have try 3 computers, always got this error and I have try scan the disk errors but not errors were found.😂

**Comment by rzhao271** [comment]
@wuzhiming if you're still using build-tools, have you tried cd-ing to the `.electron_build_tools/third_party/goma` directory, and then running `goma_auth.bat login` (if you need to log in) or `goma_ctl.bat status` (if you don't and just want to check goma's status) first?
I also suspect you might be on the wrong version of Python -- does the Python from `depot_tools` show up first for you in your PATH?

**Comment by codebytere** [comment]
closing in agreement with the above comments - this should be addressed by correcting for python version.
