### ISSUE TITLE
Document manual editing of evm configurations

### ISSUE THREAD

**Issue by erickzhao** [electron/build-tools#248]
For instances where I'd like to modify my existing configurations instead of making new ones with `e init`, it would be good to document where these configs live in the filesystem. Perhaps an `e show` subcommand that shows the location of the configs would be helpful.

**Comment by dsanders11** [comment]
@erickzhao, I think the command you want might already exist (or was added after this issue), just might need better documentation:

```
dsanders@Davids-MacBook-Pro build-tools % e show current -f
testing, /Users/dsanders/.electron_build_tools/configs/evm.testing.json
```
