### ISSUE TITLE
Feature request: release builds should have option to not generate Chromium profiles

### ISSUE THREAD

**Issue by rzhao271** [electron/build-tools#253]
I was running a release build on Windows for Electron. I had msft goma enabled, but the server was responding with many backend server errors with status 200, with the common error being of the form
```
compiler_proxy [4.9965352s]: Create file blob failed for:C:\Users\raymondzhao\work\electron-11\src\out\Release\.\../../chrome/build/pgo_profiles/chrome-win64-4280-1607005851-1da46e668e6532e71bb2ee45e7a66234b57a181e.profdata
compiler_proxy [4.9995226s]: Failed to process file request
```
It turns out that adding `chrome_pgo_phase = 0` to gn args fixes the issue, for it stops generating those files during the release build (see https://source.chromium.org/chromium/chromium/src/+/master:build/config/compiler/pgo/pgo.gni;l=1?q=build%2Fconfig%2Fcompiler%2Fpgo%2Fpgo.gni&sq=&ss=chromium%2Fchromium%2Fsrc). However, `e build` overrides gn args, so my feature request is to add a flag such as `--disable-pgo` for release builds.

**Comment by MarshallOfSound** [comment]
You can add custom args with build-tools.  Just update your args config 👍 

E.g. https://github.com/electron/build-tools/blob/master/example-configs/evm.base.yml#L10
