### ISSUE TITLE
Hand off my global git config.

### ISSUE THREAD

**Issue by marcobuschini** [electron/build-tools#257]
I mean it. Use bash scripting if you need scripts. It's included with Git for Windows.

**Comment by groundwater** [comment]
HI @marcobuschini. It sounds like you're frustrated by our build tools, which sucks. Before we continue, it is important to understand that this issue tracker and all other repos in `electron` are a workplace, and we expect workplace appropriate communication. You are welcome to this space, assuming you can abide by that.

I'm closing this as off topic.

Please wait 24 hours before re-engaging with any of the Electron properties. If, after that, you'd like to discuss this again, we'd be happy to have a discussion assuming you can provide more information, in a friendlier tone.
