### ISSUE TITLE
Login fails after batch file change

### ISSUE THREAD

**Issue by codebytere** [electron/build-tools#258]
Refs https://github.com/electron/build-tools/commit/5798b867bc174c7ef96ef1cacde0f3f4033c9b0f.

Broke login flow:

<img width="918" alt="Screen Shot 2021-03-03 at 12 18 54 PM" src="https://user-images.githubusercontent.com/2036040/109867099-f668f680-7c1a-11eb-9997-813c9c6e786c.png">

cc @rzhao271

**Comment by rzhao271** [comment]
It works for me using cmd. I will have to check with git bash, though.

**Comment by rzhao271** [comment]
Checked a few things.
Running `goma_ctl.bat status` on git bash doesn't work, but running `python goma_ctl.py status` on cmd doesn't work. 
However, running `vpython goma_ctl.py status` works alright on both, so assuming `depot_tools/vpython` is required anyway to work on Electron, I can change the code to call that instead.

**Comment by codebytere** [comment]
@rzhao271 that'd be great, ty!
