### ISSUE TITLE
Can you cross compile with the e command?

### ISSUE THREAD

**Issue by pdesantis** [electron/build-tools#310]
I'm trying to cross-compile Electron to create an arm64 Mac build on my Intel Mac. I see cross-compilation [instructions here](https://www.electronjs.org/docs/v14-x-y/development/build-instructions-gn#cross-compiling), but they are for `gn`. Is there a way to specify `target_os` & `target_cpu` when building with `e`?

**Comment by MarshallOfSound** [comment]
You can put those extra arguments in the `gen.args` section of your build tools config.

![image](https://user-images.githubusercontent.com/6634592/142953710-df3c3e3a-0910-4c99-8831-1e3ea877a1a2.png)
