### ISSUE TITLE
`e sync` overwrites `git remote` origin

### ISSUE THREAD

**Issue by EricRahm** [electron/build-tools#311]
I have a fork of `electron`, my check out locally has the official repo set as `upstream` and my fork set as `origin`. This works fine until I run `e sync` which then resets my `origin` to point at the official repo (which I cannot push to of course), ie:

```
➜ electron ✗ git remote -v
origin	git@github.com:mightyapp/electron.git (fetch)
origin	git@github.com:mightyapp/electron.git (push)
upstream	git@github.com:electron/electron.git (fetch)
upstream	git@github.com:electron/electron.git (push)

➜ electron ✗ e sync
<snip>

➜ electron ✗ git remote -v
origin	git@github.com:electron/electron.git (fetch)
origin	git@github.com:electron/electron.git (push)
upstream	git@github.com:electron/electron.git (fetch)
upstream	git@github.com:electron/electron.git (push)
```

It's possible there's a preferred way to do this, I just haven't found any docs on it and my way seems reasonable.

**Comment by MarshallOfSound** [comment]
You're looking for the `remotes` section of your build tools config, path included in screenshot.

![image](https://user-images.githubusercontent.com/6634592/142953659-ae79f1aa-2e57-499d-afe8-c929a5e5ad5b.png)

**Comment by EricRahm** [comment]
Thanks that worked for me, I wonder if adding documentation for this would be helpful for others?
