### ISSUE TITLE
You still have a master branch

### ISSUE THREAD

**Issue by mikehearn** [electron/build-tools#402]
This has just wasted large amounts of my time, wondering why the code I was reading on your site didn't seem to match the behaviour after a workaround for a different issue (checking out your repo into `~/.electron_build_tools`). The reason is that when you renamed `master` -> `main` you didn't actually rename the branch, so `master` is still there, just on some old version.

If you insist on doing this sort of thing, please ensure that a default checkout doesn't get old code.

**Comment by MarshallOfSound** [comment]
The old `master` branch is still present for _legacy_ ™️ reasons.  It does however tell you this quite loudly in your terminal when you run commands 🤷 

<img width="824" alt="image" src="https://user-images.githubusercontent.com/6634592/178579992-6549e1ce-ff09-45b8-85dc-f26bdbc75228.png">

**Comment by mikehearn** [comment]
I saw no such error, are you sure it works? Probably, Apple's default git is too old to support non-master branches.

**Comment by MarshallOfSound** [comment]
> I saw no such error, are you sure it works?

You'll only see it once every ~N hours after running a command (it occurs during the automatic update script).

> Probably, Apple's default git is too old to support non-master branches.

Git has supported those for a _long_ time, how did you install build tools?

**Comment by mikehearn** [comment]
Mm, it was rather roundabout so I can't write it down exactly. I used `npm` at first, but it failed I think because I didn't have yarn installed. So then I uninstalled it, installed yarn, reinstalled it but it didn't work for a different reason. At some point I used the workaround documented on another ticket of `cd ~/.electron_build_tools; git clone ....` and I guess that's where I ended up with the master branch. The scripts have now changed my Xcode so I guess the git version may have changed with it. At any rate, I never specifically requested the master branch. I just accepted the defaults.

Maybe the check could be done in `e init` or `e sync` so it's more obvious? The failure mode here, was that it couldn't figure out what Xcode version to use. I was looking at the code on github and thinking, this looks like it should work, why doesn't it work? Eventually I wondered if I actually was using the same code, checked and discovered it seemed old. Then I saw the branch is called "main" and guessed what must have happened.

**Comment by dsanders11** [comment]
> `main` is the default branch, I'm not aware of an installation process that would end up with you on the `master` branch

@MarshallOfSound, possibly related to electron/build-tools-installer#12? The package is still checking out `master` on initial install - a new release needs to be cut for the NPM package.
