### ISSUE TITLE
Broken and Complicated Install State Due to `xcode-select`

### ISSUE THREAD

**Issue by groundwater** [electron/build-tools#407]
If `xcode-select` points to a bad directory, then `git` breaks, and it can be non-intuitive to escape this pickle. You will receive fun messages like:

> ~ % git
> xcrun: error: unable to load libxcrun (dlopen(/Users/$ME/.electron_build_tools/third_party/Xcode/Xcode.app/Contents/Developer/usr/lib/libxcrun.dylib, 0x0005): tried: '/Users/$ME/.electron_build_tools/third_party/Xcode/Xcode.app/Contents/Developer/usr/lib/libxcrun.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/Users/$ME/.electron_build_tools/third_party/Xcode/Xcode-11.1.0.app/Contents/Developer/usr/lib/libxcrun.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))).

## HOW IT HAPPENED:

1. Somehow `npm i -g @electron/build-tools && e init --root=~/electron --boostrap=testing` installed _x86_64_ XCode binaries to `.electron_build_tools/third_party/Xcode/Xcode.app/Contents/Developer/usr/lib` instead of _arm64e_ ones.
2. `xcode-select` now points to an invalid directory for the architecture.
3. `git` fails and t̸͕̓he ẘ̶̲orl̶̮͝d fal̵͉̊ls á̸̞part

## HOW I FIXED IT:

1. I had to run `xcode-select -r` 
2. Reinstall _@electron/build-tools_ and re-init with build-tools

## HOW TO FIX IT:

Run `xcode-select -r` at the beginning of the `preinstall.js` script, and possibly elsewhere.

**Comment by MarshallOfSound** [comment]
> Somehow npm i -g @electron/build-tools && e init --root=~/electron --boostrap=testing installed x86_64 XCode binaries to .electron_build_tools/third_party/Xcode/Xcode.app/Contents/Developer/usr/lib instead of arm64e ones.

Ah I think this is a nasty side effect of a bug in `@electron/build-tools` where it checks out `master` instead of `main` which then resulted in a fallback Xcode being used which _isn't_ a universal build 😓

**Comment by georgexu99** [comment]
Commenting in case this is helpful:

When I ran into this issue, `e sync` pointed to `/Users/$ME/.electron_build_tools/third_party/Xcode/Xcode.app`, in this case Xcode 11.x.y (which doesn't support arm64). Build-tools also downloaded a copy of Xcode 13.x.y in `third_party/Xcode`, so the issue I believe was fixed somewhat for me by renaming my Xcode 13 to "Xcode.app"

**Comment by codebytere** [comment]
Closed by latest release of `build-tools-installer`
