### ISSUE TITLE
CANT FIND MODULE JS-YAML

### ISSUE THREAD

**Issue by VIXI0** [electron/build-tools#408]
For anyone having this issue
 just get the js-yaml.js from the offical repo
 save it under src 
then change src\evm-config.js
 const yml = require('.s-yaml'); TO const yml = require('./js-yaml');
notice that now im using the file localy 

this is a workaround until this issue is fixed

**Comment by VIXI0** [comment]
_If you have any doub, I even try instaling it globally and reinstalling every thing_

**Comment by codebytere** [comment]
This is in `package.json`, so i think unfortunately this is a local issue.
