### ISSUE TITLE
`e cherry-pick` fails to process certain Gerrit PR descriptions

### ISSUE THREAD

**Issue by ppontes** [electron/build-tools#412]
The `e cherry-pick` command fails to parse the bug number from the description in certain Gerrit PRs, due to a difference in how the bug number is represented. Example:

https://chromium-review.googlesource.com/c/chromium/src/+/3758469 

This results in the bug number or the CVE nr. (when used with --security) not being added automatically to the cherry-pick PR release notes.

**Comment by codebytere** [comment]
Closed in https://github.com/electron/build-tools/pull/413
