### ISSUE TITLE
How to cross compile macOS x64 on arm64 (and vice versa)?

### ISSUE THREAD

**Issue by stefansundin** [electron/build-tools#448]
I have an Apple M1 computer and I'd like to compile electron for x64. Is this possible?

Or do I have to get an Intel Mac?

**Comment by PhotoNomad0** [comment]
On an Apple M1 I was able to build both the x64 and arm64 architectures on Monterey using xCode 13.3.1.

**Comment by stefansundin** [comment]
@PhotoNomad0 That's great. Would you mind detailing the steps you took?

I assume that you somehow set `target_cpu = "x64"`? Were you able to build both architectures out of the same directory or did you need to somehow separate the configurations? What does your setup look like?

It would be great to have these steps well documented in the README file here.

**Comment by PhotoNomad0** [comment]
Here are some generic steps to build Electron.  But things change as new Electron versions are released.  Also the builds for each architecture can take hours or tens of hours.  Even getting all the sources can take hours.

I support a fork of Electron called Electronite and I have tried to remove anything here that would be Electronite specific.  Hopefully it works for you.  There be Dragons if the setup is not right and it's continually changing.

## build steps for x64

Mac Setup: https://github.com/electron/electron/blob/main/docs/development/build-instructions-macos.md#prerequisites

- installed yarn:
```
npm i -g yarn
```

- install node 16 and check version
```
node --version
```

- Installed Python 3.10. Download from `https://www.python.org/downloads/` .  Check by `python3 --version` .
- make sure there is a python 2 `python2 --version`. If not found you can install 2.7.18 from https://www.python.org/ftp/python/2.7.18/python-2.7.18-macosx10.9.pkg
- make sure there is a default Python installed by `python --version`. Should report 2.x.x, but If it reports 3.x.x you can install 2.7.18 from https://www.python.org/ftp/python/2.7.18/python-2.7.18-macosx10.9.pkg
- Set default python to be python 2
```
sudo cp /bin/python2 /bin/python
```

- initialize e commands:
```
git clone https://github.com/electron/build-tools
~/.electron_build_tools && (cd ~/.electron_build_tools && npm install)
``` 

- open terminal, cd to your build folder and initialize build:
```
export PATH=~/.electron_build_tools/third_party/depot_tools:~/.electron_build_tools/src:$PATH
e init --root=. -o x64 x64 -i release --goma none --use-https -f
```

For mac do (this initially loads a different version, but this has to happen before build will continue):
```
e load-xcode 13.3.0
```

- edit `nano ~/.electron_build_tools/configs/evm.x64.json`
  and add option to args:       `"target_cpu = \"x64\""`

- get the base Electron source code (this can take many hours the first time as the git cache is loaded):  
```
e sync
```
		
- checkout the correct Electron tag
```
cd ./src/electron
git fetch --all
git checkout <<desired tag or branch to build>>
cd ../..
```

- now get the Electron sources for branch
```
e sync
```

- Do build electron (takes a long time)
```
export NINJA_STATUS="[%r processes, %f/%t @ %o/s : %es] "
e build electron
```

- Test the build:
  - Do `e start` - should launch electron

- Make the release to ./src/out/x64/dist.zip
```
e build electron:dist
```

## build steps for arm64

same as above, but just replace wherever there is `x64` with `arm64`

**Comment by stefansundin** [comment]
Thanks! I really appreciate the level of details. :)

**Comment by stefansundin** [comment]
I followed these steps last week and wanted to just clarify some things from @PhotoNomad0's answer. I used macOS 13.1 on an M1 computer.

- I didn't have to manually set up Python. This might be because I use Homebrew and it might be set up through that.
- No need to manually clone into `~/.electron_build_tools`. It is automatically set up when you install with `npm i -g @electron/build-tools`.
- I didn't have to specify the xcode version with `e load-xcode`. The default works just fine.
- You are able to use a single working directory for compiling for both x64 and arm64, just use separate output directories. The fact that this is OK is documented in the `e init` output: https://github.com/electron/build-tools/blob/0efa2d1a0d3f78e838ee0dbdfd46426f042de3f2/src/e-init.js#L95-L96
  So don't use `--root` in the `e init` command. Just put them both in the same directory.
- I had to manually upgrade harfbuzz as explained in https://github.com/electron/build-tools/issues/445.

It would be nice if `e init` allowed you to pass `--args` that are automatically added to the config file.

I think there ought to be more documentation (in `README.md`) regarding how to manually manipulate the config files. There's not even any pointers that explain how they work. There's only some brief explanations on how to switch between configs, but it doesn't even explain where the config files are located or that you can/should modify them manually to achieve more advanced setups. This lack of documentation is also related to #446, i.e. a lot of relatively common operations aren't documented anywhere and it is left to the user to "figure it out" which leaves a bad taste when using this tool.

Anyway, closing this issue. Hopefully people can find it when they search for how to do this.

**Comment by PhotoNomad0** [comment]
> I followed these steps last week and wanted to just clarify some things from @PhotoNomad0's answer. I used macOS 13.1 on an M1 computer.
> 
>     * I didn't have to manually set up Python. This might be because I use Homebrew and it might be set up through that.
> 
>     * No need to manually clone into `~/.electron_build_tools`. It is automatically set up when you install with `npm i -g @electron/build-tools`.
> 
>     * I didn't have to specify the xcode version with `e load-xcode`. The default works just fine.
> 
>     * You are able to use a single working directory for compiling for both x64 and arm64, just use separate output directories. The fact that this is OK is documented in the `e init` output: https://github.com/electron/build-tools/blob/0efa2d1a0d3f78e838ee0dbdfd46426f042de3f2/src/e-init.js#L95-L96
>       
>       So don't use `--root` in the `e init` command. Just put them both in the same directory.
> 
>     * I had to manually upgrade harfbuzz as explained in [Compilation error 22-x-y on MacOS 13.1: sprintf deprecated #445](https://github.com/electron/build-tools/issues/445).
> 
> 
> It would be nice if `e init` allowed you to pass `--args` that are automatically added to the config file.
> 
> I think there ought to be more documentation (in `README.md`) regarding how to manually manipulate the config files. There's not even any pointers that explain how they work. There's only some brief explanations on how to switch between configs, but it doesn't even explain where the config files are located or that you can/should modify them manually to achieve more advanced setups. This lack of documentation is also related to #446, i.e. a lot of relatively common operations aren't documented anywhere and it is left to the user to "figure it out" which leaves a bad taste when using this tool.
> 
> Anyway, closing this issue. Hopefully people can find it when they search for how to do this.

I'm glad you found this helpful.  And your feedback is helpful for when I transition to using Ventura for building (currently using a Monterey VM running with UTM to keep the setups isolated from my system).  The challenging part is that Electron keeps updating the required build environment, and what worked in building a previous will throw errors with the next point release.  And I am supporting an Electron fork called Electronite, so the effort in maintaining build setups is 3 times the effort with just MacOS (when you add in Linux and Windows - as well as building for x86, x64, and arm architectures).
