### ISSUE TITLE
Is it possible to disable git cache?

### ISSUE THREAD

**Issue by alexciarlillo** [electron/build-tools#450]
We are in a weird situation. We build on Azure instances which have a job timeout, so after a few hours of compilation we archive everything and pass it along to another job where it is unarchived and the job continues. A recent change to how the electron version is determined [here](https://github.com/electron/electron/commit/7ca2bb5f9ccbbfdab9cd673bd6f95ca6a1dd342b#diff-2de8e3d568d3c57e75d1e2389e82d2cb1872fdf149891226ec3f0e389b908f5aR1) is now causing our later build steps to fail. The issue is that the underlying git command used here ends up referencing the git cache directory, which is not populated on instances used in later steps (since we are just unarchiving our in-process build in place). We end up with something like this:

```
Checking version from tags... (debug get-version.py script)
error: unable to normalize alternate object path: /Users/runner/.git_cache/github.com-electron-electron/objects
error: Could not read 28c237d4987d5b92a1af3bc81c6892262247ac32
error: Could not read 77cfce2a8fecffe4c44612e2b15202eabb29928c
error: Could not read 51dd6cd27c117969fe37f9c0d9d1d6fbc7176120
error: Could not read 5187f98f7b8299f03f481cd675c33a0fa97a3f1f
error: Could not read 1391ae4b2b40fafd72f87fcff56b5af792f85939
error: Could not read e03e626dc53ab7259920c5df4dd462967d82b0b9
error: Could not read f9b7be23b457823aec92e06b5900625e54786712
error: Could not read cd1b4b998a0d8df48f8c92fb9e9a2839bd55b068
error: Could not read 9976786632a3fa9d0f642f25f58072d44f10b5f3
error: Could not read 261b69bf5df8a8ca6cd9b7252dd31c4028f465b3
error: Could not read 795d2297f83dd0688e280b59b044490054da0faa
error: Could not read 1e3ede9d8d09dbbc0dcbc0a58e15761670e44907
error: Could not read d0fd053b8a6c714d8ac361ace53e38e8061ce3fc
error: Could not read be30017711b0d9a28b915d415818df8648f25531
error: Could not read ba93dc3c83963826b9210fe82ebcfaca2459557a
fatal: No tags can describe '160108c8b319c0847facd7b67eb5c2fe91ac92f5'.
Try --always, or create some tags.
```

Since the cache does not really help us at all in this build pipeline, is there any easy way to disable it? It appears that `e init` always sets this environment var.

**Comment by MarshallOfSound** [comment]
> We are in a weird situation. We build on Azure instances which have a job timeout, so after a few hours of compilation we archive everything and pass it along to another job where it is unarchived and the job continues

I'd suggest based on this instead of disabling the git cache you instead just ensure that the `electron` checkout is complete and not based on the cache.  i.e. `rm -rf src/electron && git clone electron/url/on/github src/electron && cd src/electron && git checkout {ref}`

Disabling the git cache will make this process _really_ slow

If you really want to disable it, you could edit the generated `emv.*.json` config file and remove the `GIT_CACHE` env var
