### ISSUE TITLE
Ninja removed from depot_tools

### ISSUE THREAD

**Issue by alexciarlillo** [electron/build-tools#454]
I'm not sure if this should be considered a build-tools issue or an issue for the main electron repo, but ninja is no longer included in depot_tools. Apparently it [has been deprecated](https://groups.google.com/a/chromium.org/g/chromium-dev/c/xFYvFYGQUGI) since the end of November, but I missed this and [as of 25 hours ago](https://chromium.googlesource.com/chromium/tools/depot_tools.git/+/8f41177abf2c51b2c0114af9abe9a5cd074d5014) the binaries have been removed. I didn't notice this until my CI builds started failing since I don't get the depot_tools updates in my local too often.

Sorry if this is the wrong spot for this but it's kind of a weird one. I am not sure if the approach will be to add it to DEPS in electron or alternatively handle the install from this suite of utilities.

**Comment by dsanders11** [comment]
Thanks for the report. We're aware of the issue and working on a fix - hopefully coming soon.

**Comment by dsanders11** [comment]
@alexciarlillo, this should be [fixed upstream now](https://chromium-review.googlesource.com/c/chromium/tools/depot_tools/+/4203207), so I'm going to close this now.
