### ISSUE TITLE
`e sanitize-config` should not succeed if there were schema validation errors

### ISSUE THREAD

**Issue by codebytere** [electron/build-tools#480]
Example:

```
src on git:main ❯ e sanitize-config                                            2:56PM
WARN Config file 'chromium' had the following validation errors:
[
  {
    "instancePath": "",
    "schemaPath": "#/oneOf/0/required",
    "keyword": "required",
    "params": {
      "missingProperty": "extends"
    },
    "message": "must have required property 'extends'"
  },
  {
    "instancePath": "/defaultTarget",
    "schemaPath": "#/oneOf/1/properties/defaultTarget/pattern",
    "keyword": "pattern",
    "params": {
      "pattern": "chrome"
    },
    "message": "must match pattern \"chrome\""
  },
  {
    "instancePath": "",
    "schemaPath": "#/oneOf/2/required",
    "keyword": "required",
    "params": {
      "missingProperty": "remotes"
    },
    "message": "must have required property 'remotes'"
  },
  {
    "instancePath": "",
    "schemaPath": "#/oneOf",
    "keyword": "oneOf",
    "params": {
      "passingSchemas": null
    },
    "message": "must match exactly one schema in oneOf"
  }
]
SUCCESS Sanitized contents of chromium
```

cc @dsanders11

**Comment by dsanders11** [comment]
I could go either way with this. The thinking with #421 was that schema validation at run-time would be advisory, but still allow a user to have a config which doesn't pass validation for advanced cases where they know what they're doing. E.g., the Chromium case, although I think it's fine to promote that to a "supported" config. Enforcing config validity in `e sanitize-config` may make advanced use cases more difficult in the future.

But perhaps enforcing validity should be the default and an escape hatch for advanced use cases could be provided, like an environment variable such as `EVM_CONFIG_SKIP_VALIDATE`. Or, perhaps a config-by-config basis where the the config itself can opt out of validation with a `"validateConfig": false` key.
