### ISSUE TITLE
Failed to download debian_sid_i386_sysroot.tar.xz s3.amazonaws.com return 403 http status code (Ubuntu 20.04 x64)

### ISSUE THREAD

**Issue by rvo337** [electron/build-tools#500]
While running command `e sync` reproduce this problem:

...
running 'python3 src/build/linux/sysroot_scripts/install-sysroot.py --arch=x86' returned non-zero exit status 1 in ...
Installing Debian sid i386 root image: /home/electron/electron/src/build/linux/debian_sid_i386-sysroot
Downloading https://s3.amazonaws.com/electronjs-sysroots/toolchain/b0f1f65ab3bd0232e7080bd3d89a9399f5ba07bc/debian_sid_i386_sysroot.tar.xz
**Failed to download https://s3.amazonaws.com/electronjs-sysroots/toolchain/b0f1f65ab3bd0232e7080bd3d89a9399f5ba07bc/debian_sid_i386_sysroot.tar.xz**

Source link return 403 http status code and this breaks `e sync`.

### Steps:
1. e build
2. e sync
3. cd src/electron
4. git checkout v14.2.9
5. e sync

### Operating System

Ubuntu 20.04 x64

### Expected Behavior
e sync success finished

### Actual Behavior
e sync failed with error

### Additional Information
I just tried two ways (electron official documentation; build-tools) and both have failed result

I tried change source link (on https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/23d12100f83139fc55349a841214d5d0bbd85a8d/debian_sid_i386_sysroot.tar.xz), but `gclient sync -f` / `e sync` rewrite my changes.

**Comment by jazzhuang** [comment]
I got the same trouble when I "git checkout v16.0.6"

**Comment by MarshallOfSound** [comment]
Electron 16 is no longer supporter, neither is any version of Electron that depends on our old sysroot storage location.  Newer Electron versions have their sysroots hosted on `dev-cdn.electronjs.org`.

E.g. https://dev-cdn.electronjs.org/linux-sysroots/b0f1f65ab3bd0232e7080bd3d89a9399f5ba07bc/debian_sid_i386_sysroot.tar.xz
