### ISSUE TITLE
Octokit should cache on CI status check so we don't auth every single time

### ISSUE THREAD

**Issue by codebytere** [electron/build-tools#507]
As of now, you need to go through the https://github.com/login/device authorization flow every single time you run `e ci status` which can be cumbersome. We should cache that somehow so you only need to re-auth every day maybe?

```
electron on git:main ❯ e ci status                                 3:54PM
This @electron/build-tools script requires GitHub Authentication
Open this page in your browser: https://github.com/login/device
Enter code: XXXX-XXXX
```

**Comment by dsanders11** [comment]
I think this can already be accomplished, it's just not really documented. There are two ways you can avoid the auth every single time:

* #364 lets you use your authenticated session with `gh` CLI
* d8686463a837540450d39d4689d9d1353043e970 lets you do `eval $(e gh-auth --shell)`

**Comment by codebytere** [comment]
Closing as complete given above info!
