### ISSUE TITLE
build eletron 28-x-y  (windows)error:  "ValueError: path is on mount '\\\\history_cluster_types.mojom-webui.js', start on mount '\\\\'"

### ISSUE THREAD

**Issue by EladBahar** [electron/build-tools#544]
### Operating System

Windows 10 (19045)

### Expected Behavior

e build should work and build electron 28 version

### Actual Behavior

build fail to due python issues after few minutes

### To Reproduce

try to build electron 28-x-y

### Screenshots

![image](https://github.com/electron/build-tools/assets/6461532/936c0201-9bd6-4ca6-bcce-97a2ef5c0ec7)

**Comment by codebytere** [comment]
hey @EladBahar - thanks for surfacing this! We're aware of it and seeing it in our own testing as well. We're investigating and should hopefully have a resolution soon.

**Comment by EladBahar** [comment]
Cool, thanks @codebytere
BTW this https://github.com/chromiumembedded/cef/issues/3506 helped me overcome this issue for now

**Comment by codebytere** [comment]
@EladBahar amazing! you're ahead of us - thanks for the pointer 😁

**Comment by codebytere** [comment]
Closed by https://github.com/electron/electron/pull/41006
