### ISSUE TITLE
How to pull a specified version of electron in e Sync? The current method is to directly pull the latest version

### ISSUE THREAD

**Issue by kingouer** [electron/build-tools#636]
How to pull a specified version of electron in e Sync? The current method is to directly pull the latest version

The content of. electron-build_tools_config. json is as follows
{
  "init": {
    "name": "my-electron",
    "sync": {
      "project": "electron",
      "remotes": {
        "origin": "https://github.com/electron/electron.git"
      },
      "target": "origin/v31.5.0",
      "with_full_chromium": true,
      "use_goma": false,
      "root": "E:/Dev/elesource",
      "full_sync": true
    }
  }
}
e init  my-electron
e sync

then
gn gen out/Release --args="import(\`"//electron/build/args/release.gn\`")"  
ninja -C out/Release electron

Open the compiled electron and find that the version is V34, not V31.5 as specified in the configuration file

**Comment by MarshallOfSound** [comment]
No idea what that config JSON is, my guess is you asked some kind of AI assistant for help?

Regardless there are docs on how to do this https://github.com/electron/build-tools#building-a-specific-electron-version

**Comment by kingouer** [comment]
thank you , I would like to ask now, how to pull a specified version of electron from zero，Can't we specify the version to be pulled from scratch? Do I have to pull it before switching versions through Git?
