### ISSUE TITLE
Building electron (x64) on ubuntu result huge file of 5 GB

### ISSUE THREAD

**Issue by EladBahar** [electron/build-tools#640]
### Operating System

 Ubuntu 24.04 x64
 
### Expected Behavior

im trying to build electron (31-x-y) on  Ubuntu 24.04 x64 usinging the following commands:
`e init release-x64 -i release --root=~/src/electron --reclient=none  --target-cpu=x64`
`e sync`  -> check out branch 31-x-y, and run sync agin  -> `e build`  
 electron file should be ~150MB

### Actual Behavior

electron is 5GB!

### Screenshots

![image](https://github.com/user-attachments/assets/c33d285d-f7c1-4aae-8c04-4622f3fa81df)

### Additional Information

Win / MacOs results are fine...

**Comment by MarshallOfSound** [comment]
You need to strip the symbols off the binary, see https://github.com/electron/electron/blob/main/script/strip-binaries.py or call `strip` manually
