### ISSUE TITLE
Some questions about reclient

### ISSUE THREAD

**Issue by wujinli** [electron/build-tools#654]
Hi, all.

Since I am not a maintainer, I do not have permission to use the reclient, but I want to deploy one.
I'm not sure if it's appropriate to raise an issue here, but I'd like to ask some questions:
1. Does your reclient support Windows compilation? From the historical issues, it seems to be supported.
2. Is there any introduction to the backend deployment of reclient? I want to try to make one myself.
3. If it is compiled for Windows, is the backend of reclient also for Windows, or is it cross-compilation on linux? Are there any matters that need to be paid attention to?

**Comment by codebytere** [comment]
> Does your reclient support Windows compilation?

Yes, it does.

> Is there any introduction to the backend deployment of reclient?

Unfortunately no, not that's publicly available.

> If it is compiled for Windows, is the backend of reclient also for Windows, or is it cross-compilation on linux.

The backend is also for Windows, yes.
