### ISSUE TITLE
Why is the build process quite slow even though there is still plenty of CPU and RAM available?

### ISSUE THREAD

**Issue by alirv90** [electron/build-tools#677]
I build on Mac M1 Pro 16GB
MacOS 15.0.1

```
e init release -i release --root=.
e sync
e build
```

Only using under 20% CPU, 50% memory, the speed is quite slow.
Same issue when I build on Thinkpad with Window 10.

I want to ask if this is an issue or if it's normal, and if there is any way to speed it up?

Thank you!

**Comment by alirv90** [comment]
I tried with:

```
e build --no-remote
```

And it worked.

**Comment by SuperDisk** [comment]
Tried this myself and indeed `--no-remote` lets the build peg my CPU, which is what I want. What does the flag even do?
