### ISSUE TITLE
Support using two different configs in different terminals

### ISSUE THREAD

**Issue by MarshallOfSound** [electron/build-tools#72]
I want to be able to `evm use foo` in one shell and `evm use bar` in the other shell and both to still work.  `nvm` supports this so technically it must be possible to set this kind of thing up

**Comment by ckerr** [comment]
This already exists: what I do is `export EVM_CURRENT=foo` in one shell and `export EVM_CURRENT=bar` in the other shell and you're good to go.

**Comment by ckerr** [comment]
...though, one thing `export EVM_CURRENT=foo` _doesn't_ do is let you set things up s.t. one _always_ has a clean slate upon opening a new shell.

From the description in the PR for #75 with the discussion of a randomly-generated session id -- are you wanting to be able to start from a clean slate every time you open a shell?
