### ISSUE TITLE
Ensure global git settings are correct on windows

### ISSUE THREAD

**Issue by MarshallOfSound** [electron/build-tools#81]
```
$ git config --global core.autocrlf false
$ git config --global core.filemode false
$ git config --global branch.autosetuprebase always
```

Not sure if we should set these automatically 🤔 But we should definitely tell users they are wrong

**Comment by Volune** [comment]
> But we should definitely tell users they are wrong

@MarshallOfSound  Hi, can you explain why other global settings are wrong? Shouldn't that be settings local to electron project instead?

**Comment by MarshallOfSound** [comment]
@Volune These are what the chromium repository require / reccomend.  Without them behavior of things like git cache and gn re-gens are undefined / not working as expected
