### ISSUE TITLE
Goma hangs on first run

### ISSUE THREAD

**Issue by samuelmaddock** [electron/build-tools#91]
OS: Windows 10 64-bit

If Goma hasn't been started yet, `e build` seems to hang when ensuring it's started.
```
D:\work\electron>e build
Running "goma_ctl.py ensure_start" in D:\work\build-tools\third_party\goma
Terminate batch job (Y/N)? y

D:\work\electron>e build
Running "goma_ctl.py ensure_start" in D:\work\build-tools\third_party\goma
Not logged in
Running "D:\work\build-tools\third_party\depot_tools\gn.bat gen "out/Testing" --args="import(\"//electron/build/args/testing.gn\") import(\"D:\work\build-tools\third_party\goma.gn\")"" in D:\work\electron\master\src
Done. Made 12190 targets from 2156 files in 12242ms
```

To reproduce, kill `compiler_proxy.exe` in the task manager then run `e build` again.

**Comment by MarshallOfSound** [comment]
I've seen this on windows too, cc @jkleinsc who I think has a script somewhere that can correctly launch goma on windows without the hang

**Comment by jkleinsc** [comment]
@marshallofsound https://github.com/electron/electron/blob/master/script/start-goma.ps1 is what we use for CI
