### ISSUE TITLE
Compilation error .o file

### ISSUE THREAD

**Issue by evgen-ai** [electron/build-tools#99]
Hi, when I try to build the Electron 4.2.12 build at some point the error falls: 
`[2889/34291] ACTION // electron: build_electron_definitions (// build / toolchain / mac: clang_x64)
FAILED: gen / electron / tsc / typings / electron.d.ts
python ../../electron/build/npm-run.py --silent gn-typescript-definitions - / Users / evgen / Documents / webrtc / electron-gn / electron / src / out / Testing / gen / electron /tsc/typings/electron.d.ts
NPM script 'gn-typescript-definitions' failed with code '1':`

After that, an error occurs on a random .o file, for example:
`[2938/34291] OBJCXX obj / skia / skia_metal / GrMtlRenderTarget.o
ninja: build stopped: subcommand failed.`

I'm building on macOs mojave 10.14.6, xcode 11.3.1
P.S. progress is moving very fast and reaches 3600 in about a minute

**Comment by MarshallOfSound** [comment]
Electron `4.2` is not a supported release line so we won't be making changes to build tools to support it, can you try `master` or a supported release line
